// import bcrypt from 'bcryptjs';
import bcrypt from 'bcryptjs';

// const data = {
const users = [
  {
    name: 'John Doe',
    email: 'test@admin.com',
    password: bcrypt.hashSync('password1'),
    isAdmin: true,
  },
  {
    name: 'Emily Doe',
    email: 'test@test.com',
    password: bcrypt.hashSync('password2'),
    isAdmin: false,
  },
  {
    name: 'Tomato Joe',
    email: 'tomatoj@mail.com',
    password: bcrypt.hashSync('password3'),
    isAdmin: false,
  },
  {
    name: 'Loca Poka',
    email: 'lokap@mail.com',
    password: bcrypt.hashSync('password4'),
    isAdmin: false,
  },
];
const products = [
  {
    name: 'Pen',
    slug: 'Pen',
    category: 'Pens',
    image: '/images/pen_set.jpg',
    price: '10.99',
    brand: 'Sanrio',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Cute sky blue pen',
  },
  {
    name: 'Bunny Pen',
    slug: 'Bunny Pen',
    category: 'Pens',
    image: '/images/pen.webp',
    price: '12.99',
    brand: 'Sanrio',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Cinaroll sky blue pen',
  },
  {
    name: 'Light Blue Pen',
    slug: 'Light Blue pen',
    category: 'Pens',
    image: '/images/bluepen.jpeg',
    price: '12.99',
    brand: 'Sanrio',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Light sky blue pen',
  },
  {
    name: 'Sticker',
    slug: 'sticker',
    category: 'Sticker',
    image: '/images/stickers.webp',
    price: '10.99',
    brand: 'Kreative',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Variety stickers',
    isFeatured: true,
    banner: '/images/stickers.webp',
  },
  {
    name: 'Custom Paper',
    slug: 'paper',
    category: 'Paper',
    image: '/images/custom_paper.jpeg',
    price: '19.99',
    brand: 'Kreative',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Variety paper',
    isFeatured: true,
    banner: '/images/custom_paper.jpeg',
  },
  {
    name: 'Stationery',
    slug: 'Stationery',
    category: 'Paper',
    image: '/images/sationery.png',
    price: '19.99',
    brand: 'Saty',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Office supplies',
    isFeatured: true,
    banner: '/images/sationery.png',
  },
  {
    name: 'Notebook',
    slug: 'Notebook',
    category: 'Notebook',
    image: '/images/notebook-4.webp',
    price: '7.99',
    brand: 'Paowei',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Plain notebook',
  },
  {
    name: 'Ghosts Notebook',
    slug: 'Ghosts Notebook',
    category: 'Notebook',
    image: '/images/notebook.webp',
    price: '10.99',
    brand: 'Paowei',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Spooky notebook',
    isFeatured: true,
  },
  {
    name: 'Cozy Notebook',
    slug: 'Cozy Notebook',
    category: 'Notebook',
    image: '/images/notebook-3.webp',
    price: '10.99',
    brand: 'Paowei',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Colorful notebook',
  },
  {
    name: 'Puppy Coaster',
    slug: 'Puppy Coaster',
    category: 'Coaster',
    image: '/images/coaster.webp',
    price: '15.99',
    brand: 'Home Essentials',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Wooden Coaster',
  },
  {
    name: 'Folder',
    slug: 'Folder',
    category: 'Organization',
    image: '/images/folder.jpeg',
    price: '9.99',
    brand: 'Fun Supply',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Colorful folder',
  },
  {
    name: 'Pencil Holder',
    slug: 'Pencil Holder',
    category: 'Organization',
    image: '/images/pencil-holder.jpeg',
    price: '15.99',
    brand: 'Home Essentials',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Desk organization',
  },
  {
    name: 'Art Stickies',
    slug: 'Art Stickies',
    category: 'Paper',
    image: '/images/stickies.jpeg',
    price: '8.99',
    brand: 'Kreative',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Art stickies',
  },

  {
    name: 'Fruit Stickies',
    slug: 'Fruit Stickies',
    category: 'Paper',
    image: '/images/sticky-notes-2.jpeg',
    price: '12.99',
    brand: 'Kreative',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Art stickies',
  },
  {
    name: 'Cute Stickies',
    slug: 'Cute Stickies',
    category: 'Paper',
    image: '/images/sticky-notes.jpeg',
    price: '12.99',
    brand: 'Kreative',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Colorful stickies',
  },
  {
    name: 'Desk Accesories',
    slug: 'Desk Accesories',
    category: 'Paper',
    image: '/images/desk-pad.webp',
    price: '25.00',
    brand: 'Home Essentials',
    rating: '0',
    numReviews: '0',
    inStock: '20',
    description: 'Leather Desk Pad',
  },
];
// };

// export default data;
export { users, products };
